xcache: &cache
  image: drillster/drone-volume-cache
  mount: [ '/drone/docker', './node_modules' ]
  volumes: [ '/tmp/cache:/cache' ]
ssh_conf: &ssh_conf
  image: shynome/alpine-drone-ci
  secrets: [ ssh_key ]
  ssh_conf: |
    Host *
      User root
      StrictHostKeyChecking no
    Host tu.wsl.fun
      HostName 42.159.134.18

pipeline:

  restore-cache:
    <<: *cache
    restore: true

  install:
    image: shynome/alpine-drone-ci
    volumes: [ "npm:/root/.npm" ]
    commands:
    - echo $DRONE_PREV_COMMIT_SHA 
    - deploy build node --install-only
  rebuild-node-cache:
    <<: *cache
    mount: [ './node_modules' ]
    rebuild: true

  build:
    image: node:carbon
    commands:
    - npm run build -- --log-level 2
    - npm run set_tags
    
  publish:
    image: plugins/docker
    repo: ${DRONE_REPO}
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    storage_path: /drone/docker

  deploy:
    <<: *ssh_conf
    deploy: docker to tu.wsl.fun core_tu ${DRONE_REPO}

  rebuild-docker-cache:
    <<: *cache
    mount: [ '/drone/docker' ]
    rebuild: true
