xcache: &cache
  image: drillster/drone-volume-cache
  mount: [ '/drone/docker', './node_modules' ]
  volumes: [ '/tmp/cache:/cache' ]

pipeline:

  restore-cache:
    <<: *cache
    restore: true

  install:
    image: node:carbon
    commands:
    - npm i
  rebuild-node-cache:
    <<: *cache
    mount: [ './node_modules' ]
    rebuild: true

  build:
    image: node:carbon
    commands:
    - npm run build -- --log-level 2
    - npm run set_tags
    
  publish:
    image: plugins/docker
    repo: shynome/tu.duowan.com
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    storage_path: /drone/docker

  rebuild-docker-cache:
    <<: *cache
    mount: [ '/drone/docker' ]
    rebuild: true
