xcache: &cache
  image: drillster/drone-volume-cache
  mount: [ '/drone/docker', './node_modules' ]
  volumes: [ '/tmp/cache:/cache' ]

pipeline:

  restore-cache:
    <<: *cache
    restore: true

  build:
    image: node:carbon
    commands:
    - npm i --ignore-scripts
    - npm run build -- --log-level 1
    - npm run set_tags
    
  publish:
    image: plugins/docker
    repo: shynome/tu.duowan.com
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    storage_path: /drone/docker

  rebuild-cache:
    <<: *cache
    rebuild: true
